Query update animals table
SimonGideon/Vet-clinic-database pull request #2
Opened 2023-01-25 22:24 UTC by SimonGideon

# Project requirements
Add a column species of type string to your animals table. Modify your schema.sql file.
Insert the following data:
Animal: His name is Charmander. He was born on Feb 8th, 2020, and currently weighs -11kg. He is not neutered and he has never tried to escape.
Animal: Her name is Plantmon. She was born on Nov 15th, 2021, and currently weighs -5.7kg. She is neutered and she has tried to escape 2 times.
Animal: His name is Squirtle. He was born on Apr 2nd, 1993, and currently weighs -12.13kg. He was not neutered and he has tried to escape 3 times.
Animal: His name is Angemon. He was born on Jun 12th, 2005, and currently weighs -45kg. He is neutered and he has tried to escape once.
Animal: His name is Boarmon. He was born on Jun 7th, 2005, and currently weighs 20.4kg. He is neutered and he has tried to escape 7 times.
Animal: Her name is Blossom. She was born on Oct 13th, 1998, and currently weighs 17kg. She is neutered and she has tried to escape 3 times.
Animal: His name is Ditto. He was born on May 14th, 2022, and currently weighs 22kg. He is neutered and he has tried to escape 4 times.
Remember to add these insertions to your data.sql file.
Inside a transaction update the animals table by setting the species column to unspecified. Verify that change was made. Then roll back the change and verify that the species columns went back to the state before the transaction.
Inside a transaction:
Update the animals table by setting the species column to digimon for all animals that have a name ending in mon.
Update the animals table by setting the species column to pokemon for all animals that don't have species already set.
Commit the transaction.
Verify that change was made and persists after commit.
Take a screenshot of the results of your actions.
Now, take a deep breath and... Inside a transaction delete all records in the animals table, then roll back the transaction.
After the rollback verify if all records in the animals table still exists. After that, you can start breathing as usual ;)
Take a screenshot of the results of your actions.
Inside a transaction:
Delete all animals born after Jan 1st, 2022.
Create a savepoint for the transaction.
Update all animals' weight to be their weight multiplied by -1.
Rollback to the savepoint
Update all animals' weights that are negative to be their weight multiplied by -1.
Commit transaction
Take a screenshot of the results of your actions.
Remember to add all these transactions to your queries.sql file.
Write queries to answer the following questions:
How many animals are there?
How many animals have never tried to escape?
What is the average weight of animals?
Who escapes the most, neutered or not neutered animals?
What is the minimum and maximum weight of each type of animal?
What is the average number of escape attempts per animal type of those born between 1990 and 2000?
Take a screenshot of the results of your queries.
Remember to add these queries to your queries.sql file.
Remember to add screenshots with the results of your queries and with the results of your play with transactions to your Pull Request description

## Trasaction
![Delete](https://user-images.githubusercontent.com/61404403/214704518-28222608-e477-4929-a4d9-4931b17f1f58.png)
![roll back](https://user-images.githubusercontent.com/61404403/214704493-d3d77d5a-a7b2-49ff-b5b5-a78664285af6.png)
![species](https://user-images.githubusercontent.com/61404403/214704508-788fef65-6341-44ac-a814-668c19be7b72.png)

## Queries
![average](https://user-images.githubusercontent.com/61404403/214704723-c98dd711-24a8-4a33-bcc0-476315fef886.png)
![count](https://user-images.githubusercontent.com/61404403/214704734-15060a99-ce4f-4df5-a46b-8212fe1cd79f.png)
![escape attampts](https://user-images.githubusercontent.com/61404403/214704739-36f283a8-5225-4141-8eb3-1aae936b45b2.png)
![image](https://user-images.githubusercontent.com/61404403/214705209-010d3db6-df13-46ca-b607-cf15f099ac85.png)
![image](https://user-images.githubusercontent.com/61404403/214705309-cdd83378-c074-4a8a-9542-3f2cedf6835f.png)
![image](https://user-images.githubusercontent.com/61404403/214705459-40c849a4-6bac-4b8a-93e0-5de3eff3500d.png)

2023-01-25 23:18 UTC, Gambit142 requested changes
Hi @SimonGideon 👋, 

Good job so far!

## Highlights
- README.md file is professional ✔️ 
- Everything that creates or changes the table structure is saved in the schema.sql file.
- Everything that populates tables with data is saved in the data.sql file.
- Everything that is a query that helps to analyze is saved in the queries.sql file.

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-25 23:18 UTC, Gambit142 commented on queries.sql
> +SELECT neutered, COUNT(*) FROM animals GROUP BY neutered ORDER BY COUNT(*) DESC LIMIT 1;
- [ ] This query will return the wrong result. The query should return which group escapes the most in terms of _**neutered**_ animals and _**non-neutered**_ animals. To return the right data, you would have to select the `neutered` column and the `AVG(escape_attempts)` or `MAX(escape_attempt)` and then group by neutered. All you have to do is replace `COUNT(*)` with either `AVG(escape_attempts)` or `MAX(escape_attempt)`

2023-01-30 17:29 UTC, SimonGideon commented on data.sql
> +
![image](https://user-images.githubusercontent.com/61404403/215549383-d3a6dc17-a12d-47e1-a2d2-f2f1f175e794.png)

![image](https://user-images.githubusercontent.com/61404403/215549237-61f2b270-72dc-4ff0-8aa4-1217cd4d29cd.png)

:+1: @Gambit142 I request you check that the values of `weight_kg` of `Blossom` and `Boarmon` are correct as Outlined in the Question.

2023-01-30 17:32 UTC, SimonGideon commented on data.sql
>  VALUES('Devimon', DATE '2017-05-12',5,true,11);
:smile: Noted. Corrected in the future commits.

2023-01-30 18:49 UTC, SimonGideon commented on queries.sql
> +SELECT neutered, COUNT(*) FROM animals GROUP BY neutered ORDER BY COUNT(*) DESC LIMIT 1;
Done

2023-01-30 19:21 UTC, Davidosky007 approved these changes
Hi @SimonGideon 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Well written PR description 👍 
* Good looking readme file 👍 
* Proper use of Gitflow 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-30 19:23 UTC, merged

2023-01-30 19:56 UTC, Gambit142 commented on data.sql
> +
Hi @SimonGideon 👋, please read my statement again. I said `apart from`. You ought to input negative values for most of the animals in this milestone. 👍

2023-01-30 20:10 UTC, SimonGideon commented on data.sql
> +
@Gambit142 :slightly_smiling_face: Got it man. Thanks